---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "vars-{{ ansible_os_family | lower }}.yml"

- include_tasks: setup-redhat.yml
  when: ansible_os_family | lower == 'redhat'

- name: R | Install R packages minimal
  command: >-
    Rscript --slave --no-save --no-restore-history -e "
      if (! ('{{ item }}' %in% installed.packages()[,'Package'])) {
        install.packages(pkgs='{{ item }}', repos=c('{{ r_cran_mirror }}'));
        print('Added');
      } else {
        print('Already installed');
      }
    "
  register: r_result
  failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
  changed_when: "'Added' in r_result.stdout"
  with_items:
    - shiny
  loop_control:
    label: "{{ item }}"