---

- name: Install | Dependencies
  ansible.builtin.apt:
    name: "{{ ' '.join(r_dependencies).split() }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
